service:
  http:
    unavailable:
      retry-after: 10
  image:
    charta:
      maximum-dimensions:
        width: 20000
        height: 50000
    fragment:
      maximum-dimensions:
        width: 5000
        height: 5000
    type: BMP
    parent-path: ./chartas
    lock:
      trying-time: 10

server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher