service:
  http:
    unavailable:
      retry-after: 10
  image:
    maximum-dimensions:
      width: 20000
      height: 50000
    type: BMP
    parent-path: ./chartas
    lock:
      trying-time: 10

server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher